apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-processor
  labels:
    app: queue-processor
    name: queue-processor
spec:
  scaleTargetRef:
    name: queue-processor
  minReplicaCount: 0 #Change to define how many minimum replicas you want
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: kedatest
      queueLength: '5'
    authenticationRef:
      name: trigger-auth-service-bus